version: "3.4"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Sport_simulator
    ports:
      - "3000:3000"
    depends_on:
      - db


# version: '3.4'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: salesbetes
#     #env_file: .docker/.env
#     volumes:
#       - .:/salesbetes
#       - './storage:/salesbetes/storage'
#       - /salesbetes/vendor
#     depends_on:
#       - 'postgresql'
#       - 'redis'

#   postgresql:
#     image: postgres:10.0-alpine
#     container_name: backend_postgres
#     environment:
#       POSTGRES_PASSWORD: pgpassword
#       POSTGRES_DB: backend_development
#       POSTGRES_USER: postgres
#       POSTGRES_HOST: postgresql
#       POSTGRES_PORT: 5432
#       PGDATA: /var/lib/postgresql/data/pg_data

#   redis:
#     image: 'redis:4.0-alpine'
#     container_name: salesbetes_redis

  # sidekiq:
  #   depends_on:
  #     - 'postgresql'
  #     - 'redis'
  #   build: .
  #   env_file: .docker/.env
  #   command: bundle exec sidekiq
  #   volumes:
  #     - '.:/backend'
  #     - './storage:/backend/storage'
  #     - /backend/vendor

  # sidekiq_web:
  #   depends_on:
  #     - 'redis'
  #   image: aschzero/sidekiq-web
  #   container_name: backend_sidekiq_web
  #   env_file: .docker/.env
  #   expose:
  #     - 3030